apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask_hello
  labels:
    app: flask_hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask_hello
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: flask_hello
    spec:
      containers:
        - name: flask_hello
          image: localhost:4000/flask_hello:latest
          ports:
            - containerPort: 5000
              name: microport
