apiVersion: v1
kind: Service
metadata:
  name: flask-hello    # flask_hello → flask-hello
  labels:
    app: flask-hello   # flask_hello → flask-hello
spec:
  type: NodePort
  selector:
    app: flask-hello   # flask_hello → flask-hello
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000