apiVersion: v1
kind: Service
metadata:
  name: flask_hello
  labels:
    app: flask_hello
spec:
  type: NodePort
  selector:
    app: flask_hello
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31000
